/**
 * @file dashboard.config.js
 * @description Dashboard configuration for all roles and components
 * @author Sherif Talaat
 * @version 1.0.0
 * @date 2025-12-19
 *
 */

import {
  Briefcase,
  DollarSign,
  Users,
  Clock,
  Send,
  TrendingUp,
  Activity,
  PieChart,
  Calendar,
  Target,
  ThumbsUp,
  FileText,
  MessageSquare,
  UserPlus,
  CheckCircle,
  FileCheck,
  AlertCircle,
  Home,
  Settings,
  Bell,
  HelpCircle,
  LogOut,
  Layers,
  Award,
  BarChart,
  Mail,
  FolderOpen,
  Shield,
} from "lucide-react";

export const ROLES = {
  CLIENT: "client",
  FREELANCER: "freelancer",
  COMPANY: "company",
  JOBSEEKER: "jobseeker",
};

// Role-specific metrics configuration
export const ROLE_METRICS = {
  [ROLES.CLIENT]: {
    title: "Client Dashboard",
    description: "Manage your projects and talent",
    metrics: [
      {
        id: "activeProjects",
        label: "Active Projects",
        value: "12",
        change: "+2",
        trend: "up",
        icon: Briefcase,
        color: "var(--color-accent-pink)",
        details: "3 behind schedule",
      },
      {
        id: "totalSpend",
        label: "Total Spend",
        value: "$42,580",
        change: "+8.2%",
        trend: "up",
        icon: DollarSign,
        color: "var(--color-vivid-pink)",
        details: "Monthly budget: $50k",
      },
      {
        id: "openPositions",
        label: "Open Positions",
        value: "5",
        change: "-1",
        trend: "down",
        icon: Users,
        color: "var(--color-primary)",
        details: "2 urgent hires",
      },
      {
        id: "avgResponseTime",
        label: "Avg. Response Time",
        value: "4.2h",
        change: "-0.8h",
        trend: "down",
        icon: Clock,
        color: "var(--color-accent)",
        details: "Industry avg: 6h",
      },
    ],
  },
  [ROLES.FREELANCER]: {
    title: "Freelancer Dashboard",
    description: "Track your projects and earnings",
    metrics: [
      {
        id: "activeProjects",
        label: "Active Projects",
        value: "3",
        change: "+1",
        trend: "up",
        icon: Briefcase,
        color: "var(--color-accent-pink)",
        details: "All on track",
      },
      {
        id: "earnings",
        label: "Earnings",
        value: "$8,250",
        change: "+15.5%",
        trend: "up",
        icon: DollarSign,
        color: "var(--color-vivid-pink)",
        details: "Target: $10k/mo",
      },
      {
        id: "proposalsSent",
        label: "Proposals Sent",
        value: "24",
        change: "+6",
        trend: "up",
        icon: Send,
        color: "var(--color-primary)",
        details: "12% response rate",
      },
      {
        id: "successRate",
        label: "Job Success Rate",
        value: "92%",
        change: "+3%",
        trend: "up",
        icon: TrendingUp,
        color: "var(--color-accent)",
        details: "Platform avg: 85%",
      },
    ],
  },
  [ROLES.COMPANY]: {
    title: "Company Dashboard",
    description: "Manage team and hiring pipeline",
    metrics: [
      {
        id: "teamActivity",
        label: "Team Activity",
        value: "87%",
        change: "+5%",
        trend: "up",
        icon: Activity,
        color: "var(--color-accent-pink)",
        details: "12 active members",
      },
      {
        id: "hiringPipeline",
        label: "Hiring Pipeline",
        value: "18",
        change: "+4",
        trend: "up",
        icon: Users,
        color: "var(--color-vivid-pink)",
        details: "5 in final round",
      },
      {
        id: "budgetOverview",
        label: "Budget Used",
        value: "68%",
        change: "-12%",
        trend: "down",
        icon: PieChart,
        color: "var(--color-primary)",
        details: "$25k remaining",
      },
      {
        id: "avgHireTime",
        label: "Avg. Hire Time",
        value: "14d",
        change: "-3d",
        trend: "down",
        icon: Calendar,
        color: "var(--color-accent)",
        details: "Goal: 10 days",
      },
    ],
  },
  [ROLES.JOBSEEKER]: {
    title: "Job Seeker Dashboard",
    description: "Track applications and interviews",
    metrics: [
      {
        id: "appliedJobs",
        label: "Applied Jobs",
        value: "15",
        change: "+3",
        trend: "up",
        icon: Briefcase,
        color: "var(--color-accent-pink)",
        details: "5 new this week",
      },
      {
        id: "interviews",
        label: "Interviews",
        value: "4",
        change: "+2",
        trend: "up",
        icon: Calendar,
        color: "var(--color-vivid-pink)",
        details: "2 scheduled",
      },
      {
        id: "skillsMatch",
        label: "Skills Match",
        value: "87%",
        change: "+5%",
        trend: "up",
        icon: Target,
        color: "var(--color-primary)",
        details: "3 skills to improve",
      },
      {
        id: "recommendations",
        label: "Recommendations",
        value: "12",
        change: "+4",
        trend: "up",
        icon: ThumbsUp,
        color: "var(--color-accent)",
        details: "Based on profile",
      },
    ],
  },
};

// Sample activity data for RecentActivity component
export const SAMPLE_ACTIVITIES = {
  [ROLES.CLIENT]: [
    {
      id: 1,
      type: "proposal",
      description: "New proposal received for React Developer position",
      time: "2 hours ago",
      user: "sarah.john",
      read: false,
      priority: "high",
    },
    {
      id: 2,
      type: "message",
      description: "Message regarding project timeline changes",
      time: "4 hours ago",
      user: "alex.wong",
      read: true,
    },
    {
      id: 3,
      type: "job",
      description: "Job posting for UX Designer is now live",
      time: "1 day ago",
      read: true,
    },
    {
      id: 4,
      type: "completion",
      description: 'Project "E-commerce Dashboard" completed',
      time: "2 days ago",
      user: "dev.team",
      read: true,
      priority: "medium",
    },
  ],
  [ROLES.FREELANCER]: [
    {
      id: 1,
      type: "message",
      description: "Client sent feedback on your proposal",
      time: "1 hour ago",
      user: "techcorp.hr",
      read: false,
    },
    {
      id: 2,
      type: "proposal",
      description: "Your proposal was viewed by hiring manager",
      time: "3 hours ago",
      user: "startup.ceo",
      read: true,
    },
    {
      id: 3,
      type: "completion",
      description: 'Payment received for "Mobile App Design" project',
      time: "1 day ago",
      read: true,
      priority: "high",
    },
    {
      id: 4,
      type: "connection",
      description: "New connection request from senior designer",
      time: "2 days ago",
      user: "jane.doe",
      read: true,
    },
  ],
  [ROLES.COMPANY]: [
    {
      id: 1,
      type: "proposal",
      description: "New application for Senior Developer role",
      time: "30 minutes ago",
      user: "john.smith",
      read: false,
      priority: "high",
    },
    {
      id: 2,
      type: "message",
      description: "Candidate accepted interview invitation",
      time: "2 hours ago",
      user: "emma.jones",
      read: true,
    },
    {
      id: 3,
      type: "completion",
      description: "Hiring budget approved for Q4",
      time: "1 day ago",
      read: true,
    },
    {
      id: 4,
      type: "job",
      description: "New job posting needs approval",
      time: "2 days ago",
      read: false,
      priority: "medium",
    },
  ],
  [ROLES.JOBSEEKER]: [
    {
      id: 1,
      type: "job",
      description: "Application submitted for Frontend Developer",
      time: "1 hour ago",
      user: "tech.company",
      read: true,
    },
    {
      id: 2,
      type: "message",
      description: "Interview scheduled for next week",
      time: "3 hours ago",
      user: "hr.recruiter",
      read: false,
      priority: "high",
    },
    {
      id: 3,
      type: "completion",
      description: "Profile viewed by 5 recruiters today",
      time: "1 day ago",
      read: true,
    },
    {
      id: 4,
      type: "connection",
      description: "New job recommendation based on skills",
      time: "2 days ago",
      read: true,
    },
  ],
};

// Sample pending actions for PendingActions component
export const SAMPLE_PENDING_ACTIONS = {
  [ROLES.CLIENT]: [
    {
      id: 1,
      title: "Review proposals for React Developer",
      description: "3 new proposals need review before deadline",
      priority: "high",
      dueDate: "Tomorrow",
      completed: false,
      category: "Review",
      type: "review",
      assignedTo: "Project Manager",
    },
    {
      id: 2,
      title: "Approve invoice payment",
      description: "Invoice #INV-2023-001 for $2,500",
      priority: "medium",
      dueDate: "In 3 days",
      completed: false,
      category: "Payment",
      type: "payment",
    },
    {
      id: 3,
      title: "Respond to client message",
      description: "Client has questions about project timeline",
      priority: "low",
      dueDate: "Today",
      completed: true,
      category: "Message",
      type: "message",
      assignedTo: "You",
    },
  ],
  [ROLES.FREELANCER]: [
    {
      id: 1,
      title: "Update project deliverables",
      description: "Add new features to project plan",
      priority: "high",
      dueDate: "Today",
      completed: false,
      category: "Project",
      type: "update",
      assignedTo: "You",
    },
    {
      id: 2,
      title: "Submit weekly timesheet",
      description: "Hours worked: 32.5",
      priority: "medium",
      dueDate: "Tomorrow",
      completed: false,
      category: "Admin",
      type: "deadline",
    },
    {
      id: 3,
      title: "Send proposal to new client",
      description: "Mobile app development project",
      priority: "high",
      dueDate: "In 2 days",
      completed: false,
      category: "Proposal",
      type: "review",
    },
  ],
  [ROLES.COMPANY]: [
    {
      id: 1,
      title: "Review candidate profiles",
      description: "12 new applications for Developer role",
      priority: "high",
      dueDate: "Today",
      completed: false,
      category: "Hiring",
      type: "review",
      assignedTo: "HR Team",
    },
    {
      id: 2,
      title: "Schedule team training",
      description: "React 19 workshop for developers",
      priority: "medium",
      dueDate: "This week",
      completed: false,
      category: "Team",
      type: "meeting",
    },
    {
      id: 3,
      title: "Approve Q4 hiring budget",
      description: "Budget increase request: +15%",
      priority: "high",
      dueDate: "In 2 days",
      completed: true,
      category: "Finance",
      type: "payment",
    },
  ],
  [ROLES.JOBSEEKER]: [
    {
      id: 1,
      title: "Complete profile verification",
      description: "Upload documents for verification",
      priority: "high",
      dueDate: "Today",
      completed: false,
      category: "Profile",
      type: "update",
      assignedTo: "You",
    },
    {
      id: 2,
      title: "Prepare for interview",
      description: "Technical interview at 2 PM tomorrow",
      priority: "high",
      dueDate: "Tomorrow",
      completed: false,
      category: "Interview",
      type: "meeting",
    },
    {
      id: 3,
      title: "Update resume with new projects",
      description: "Add 3 recent projects",
      priority: "medium",
      dueDate: "This week",
      completed: true,
      category: "Profile",
      type: "update",
    },
  ],
};

// Sample job posts for RecentJobPosts component
export const SAMPLE_JOB_POSTS = {
  [ROLES.CLIENT]: [
    {
      id: 1,
      title: "Senior React Developer",
      company: "Tech Innovations Inc.",
      proposals: 24,
      budget: "$8k - $12k",
      status: "active",
      posted: "2 days ago",
      priority: "high",
    },
    {
      id: 2,
      title: "UX/UI Designer",
      company: "Creative Studio",
      proposals: 18,
      budget: "$5k - $8k",
      status: "review",
      posted: "5 days ago",
      priority: "medium",
    },
  ],
  [ROLES.FREELANCER]: [
    {
      id: 1,
      title: "Full Stack Developer",
      company: "Startup XYZ",
      proposals: 42,
      budget: "$10k - $15k",
      status: "active",
      posted: "1 day ago",
      priority: "high",
    },
    {
      id: 2,
      title: "Mobile App Developer",
      company: "App Masters",
      proposals: 31,
      budget: "$6k - $9k",
      status: "review",
      posted: "3 days ago",
      priority: "medium",
    },
  ],
  [ROLES.COMPANY]: [
    {
      id: 1,
      title: "Senior DevOps Engineer",
      company: "Your Company",
      proposals: 38,
      budget: "$120k - $150k",
      status: "active",
      posted: "1 day ago",
      priority: "high",
    },
    {
      id: 2,
      title: "Product Manager",
      company: "Your Company",
      proposals: 22,
      budget: "$90k - $130k",
      status: "draft",
      posted: "4 days ago",
      priority: "medium",
    },
  ],
  [ROLES.JOBSEEKER]: [
    {
      id: 1,
      title: "Frontend Developer",
      company: "Digital Solutions",
      proposals: 56,
      budget: "$80k - $110k",
      status: "applied",
      posted: "2 days ago",
      priority: "high",
    },
    {
      id: 2,
      title: "UI Designer",
      company: "Design Studio Pro",
      proposals: 34,
      budget: "$70k - $95k",
      status: "saved",
      posted: "5 days ago",
      priority: "medium",
    },
  ],
};

// Navigation configuration for each role
export const ROLE_NAVIGATION = {
  [ROLES.CLIENT]: [
    { id: "overview", label: "Overview", icon: Home, path: "/dashboard" },
    { id: "projects", label: "Projects", icon: Briefcase, path: "/projects" },
    { id: "talent", label: "Talent Pool", icon: Users, path: "/talent" },
    { id: "messages", label: "Messages", icon: Mail, path: "/messages" },
    { id: "reports", label: "Reports", icon: BarChart, path: "/reports" },
  ],
  [ROLES.FREELANCER]: [
    { id: "overview", label: "Overview", icon: Home, path: "/dashboard" },
    { id: "projects", label: "Projects", icon: Briefcase, path: "/projects" },
    { id: "proposals", label: "Proposals", icon: Send, path: "/proposals" },
    { id: "earnings", label: "Earnings", icon: DollarSign, path: "/earnings" },
    { id: "profile", label: "Profile", icon: UserPlus, path: "/profile" },
  ],
  [ROLES.COMPANY]: [
    { id: "overview", label: "Overview", icon: Home, path: "/dashboard" },
    { id: "team", label: "Team", icon: Users, path: "/team" },
    { id: "hiring", label: "Hiring", icon: Briefcase, path: "/hiring" },
    { id: "reports", label: "Reports", icon: BarChart, path: "/reports" },
    { id: "settings", label: "Settings", icon: Settings, path: "/settings" },
  ],
  [ROLES.JOBSEEKER]: [
    { id: "overview", label: "Overview", icon: Home, path: "/dashboard" },
    { id: "jobs", label: "Jobs", icon: Briefcase, path: "/jobs" },
    {
      id: "applications",
      label: "Applications",
      icon: FolderOpen,
      path: "/applications",
    },
    { id: "profile", label: "Profile", icon: UserPlus, path: "/profile" },
    { id: "skills", label: "Skills", icon: Award, path: "/skills" },
  ],
};

// Header navigation (common for all roles)
export const HEADER_NAVIGATION = [
  { id: "notifications", icon: Bell, label: "Notifications", hasBadge: true },
  { id: "help", icon: HelpCircle, label: "Help & Support" },
  { id: "settings", icon: Settings, label: "Settings" },
  { id: "logout", icon: LogOut, label: "Logout" },
];

// Default data when no real data is available
export const DEFAULT_DATA = {
  activities: [],
  pendingActions: [],
  recentJobs: [],
  metrics: [],
};

// Export role display names
export const ROLE_DISPLAY_NAMES = {
  [ROLES.CLIENT]: "Client",
  [ROLES.FREELANCER]: "Freelancer",
  [ROLES.COMPANY]: "Company",
  [ROLES.JOBSEEKER]: "Job Seeker",
};

// Theme settings
export const THEME_SETTINGS = {
  light: {
    primaryColor: "var(--color-primary)",
    accentColor: "var(--color-accent-pink)",
    backgroundColor: "var(--color-background)",
  },
  dark: {
    primaryColor: "var(--color-primary)",
    accentColor: "var(--color-accent-pink)",
    backgroundColor: "var(--color-background)",
  },
};

// Component visibility configuration by role
export const COMPONENT_VISIBILITY = {
  [ROLES.CLIENT]: {
    showMetrics: true,
    showRecentActivity: true,
    showRecentJobPosts: true,
    showPendingActions: true,
    showEarnings: false,
    showApplications: false,
    showTeamActivity: false,
  },
  [ROLES.FREELANCER]: {
    showMetrics: true,
    showRecentActivity: true,
    showRecentJobPosts: true,
    showPendingActions: true,
    showEarnings: true,
    showApplications: true,
    showTeamActivity: false,
  },
  [ROLES.COMPANY]: {
    showMetrics: true,
    showRecentActivity: true,
    showRecentJobPosts: true,
    showPendingActions: true,
    showEarnings: false,
    showApplications: false,
    showTeamActivity: true,
  },
  [ROLES.JOBSEEKER]: {
    showMetrics: true,
    showRecentActivity: true,
    showRecentJobPosts: true,
    showPendingActions: true,
    showEarnings: false,
    showApplications: true,
    showTeamActivity: false,
  },
};

// Export everything
export default {
  ROLES,
  ROLE_METRICS,
  ROLE_NAVIGATION,
  HEADER_NAVIGATION,
  SAMPLE_ACTIVITIES,
  SAMPLE_PENDING_ACTIONS,
  SAMPLE_JOB_POSTS,
  DEFAULT_DATA,
  ROLE_DISPLAY_NAMES,
  THEME_SETTINGS,
  COMPONENT_VISIBILITY,
};
